# **Tokenization of Paragraph/ Sentences**

In [7]:
# import Libraries
import nltk

# Ensure the punkt resource is downloaded
nltk.download('punkt') # Punkt resource is needed for sentence tokenization, punkt_tab is a specific internal representation
nltk.download('punkt_tab') # Download the resource explicitly

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [8]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nucle ar material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

In [9]:
# Tokenizing sentences (To convert it to sentences)
sent = nltk.sent_tokenize(paragraph)

In [10]:
print(sent)

['I have three visions for India.', 'In 3000 years of our history, people from all over\n               the world have come and invaded us, captured our lands, conquered our minds.', 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their culture,\n               their history and tried to enforce our way of life on them.', 'Why?', 'Because we respect the freedom of others.That is why my\n               first vision is that of freedom.', 'I believe that India got its first vision of\n               this in 1857, when we started the War of Independence.', 'It is this freedom that\n               we must protect and nurture and build on.', 'If we are not free, no one will respect us.', 'My second vision for India’s development.', 'For fift

In [11]:
len(sent)

31

In [12]:
# Tokenizing words
words = nltk.word_tokenize(paragraph)

In [13]:
print(words)

['I', 'have', 'three', 'visions', 'for', 'India', '.', 'In', '3000', 'years', 'of', 'our', 'history', ',', 'people', 'from', 'all', 'over', 'the', 'world', 'have', 'come', 'and', 'invaded', 'us', ',', 'captured', 'our', 'lands', ',', 'conquered', 'our', 'minds', '.', 'From', 'Alexander', 'onwards', ',', 'the', 'Greeks', ',', 'the', 'Turks', ',', 'the', 'Moguls', ',', 'the', 'Portuguese', ',', 'the', 'British', ',', 'the', 'French', ',', 'the', 'Dutch', ',', 'all', 'of', 'them', 'came', 'and', 'looted', 'us', ',', 'took', 'over', 'what', 'was', 'ours', '.', 'Yet', 'we', 'have', 'not', 'done', 'this', 'to', 'any', 'other', 'nation', '.', 'We', 'have', 'not', 'conquered', 'anyone', '.', 'We', 'have', 'not', 'grabbed', 'their', 'land', ',', 'their', 'culture', ',', 'their', 'history', 'and', 'tried', 'to', 'enforce', 'our', 'way', 'of', 'life', 'on', 'them', '.', 'Why', '?', 'Because', 'we', 'respect', 'the', 'freedom', 'of', 'others.That', 'is', 'why', 'my', 'first', 'vision', 'is', 'that

In [14]:
len(words)

400

#**Stemming**

In [15]:
# Download the stopwords resource
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
# import necessary Libraries
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords # Remove some common words

In [17]:
sent = nltk.sent_tokenize(paragraph)
stemmer = PorterStemmer()  # Initialize PorterStemmer

In [18]:
stopwords.words('english') # English stopwords

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [19]:
stopwords.words('arabic') # Arabic stopwords

['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل'

In [20]:
# Stemming
for i in range(len(sent)):
  words = nltk.word_tokenize(sent[i])
  words = [stemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
  sent[i] = ' '.join(words)

In [21]:
print(sent)

['i three vision india .', 'in 3000 year histori , peopl world come invad us , captur land , conquer mind .', 'from alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .', 'yet done nation .', 'we conquer anyon .', 'we grab land , cultur , histori tri enforc way life .', 'whi ?', 'becaus respect freedom others.that first vision freedom .', 'i believ india got first vision 1857 , start war independ .', 'it freedom must protect nurtur build .', 'if free , one respect us .', 'my second vision india ’ develop .', 'for fifti year develop nation .', 'it time see develop nation .', 'we among top 5 nation world term gdp .', 'we 10 percent growth rate area .', 'our poverti level fall .', 'our achiev global recognis today .', 'yet lack self-confid see develop nation , self-reli self-assur .', 'isn ’ incorrect ?', 'i third vision .', 'india must stand world .', 'becaus i believ unless india stand world , one respect us .', 'onli strength respect stre

###**Problem of Stemming:**
Produced intermediate representation of the word may not have any meaning.

Example: intelligen, fina

#**Lemmatization**

In [22]:
# Download the wordnet resource for lemmatization
nltk.download('wordnet')
nltk.download('omw-1.4') # Also often needed for WordNet lemmatization to work correctly with various languages

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [23]:
# import necessary Libraries
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [24]:
sent = nltk.sent_tokenize(paragraph)
lemmatizer = WordNetLemmatizer()     # WordNet Lemmatizer

In [25]:
# Lemmatizion
for i in range(len(sent)):
  words = nltk.word_tokenize(sent[i])
  words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words("english"))]
  sent[i] = ' '.join(words)


In [26]:
print(sent)

['I three vision India .', 'In 3000 year history , people world come invaded u , captured land , conquered mind .', 'From Alexander onwards , Greeks , Turks , Moguls , Portuguese , British , French , Dutch , came looted u , took .', 'Yet done nation .', 'We conquered anyone .', 'We grabbed land , culture , history tried enforce way life .', 'Why ?', 'Because respect freedom others.That first vision freedom .', 'I believe India got first vision 1857 , started War Independence .', 'It freedom must protect nurture build .', 'If free , one respect u .', 'My second vision India ’ development .', 'For fifty year developing nation .', 'It time see developed nation .', 'We among top 5 nation world term GDP .', 'We 10 percent growth rate area .', 'Our poverty level falling .', 'Our achievement globally recognised today .', 'Yet lack self-confidence see developed nation , self-reliant self-assured .', 'Isn ’ incorrect ?', 'I third vision .', 'India must stand world .', 'Because I believe unless 

#**Bag o fWords**

In [27]:
# import necessary libraries
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [28]:
ps = PorterStemmer()
wordnet = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)

In [29]:
corpus = []
for i in range(len(sent)):
  review = re.sub('[^a-zA-Z]', ' ', sent[i])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

In [30]:
print(sent)

['I three vision India .', 'In 3000 year history , people world come invaded u , captured land , conquered mind .', 'From Alexander onwards , Greeks , Turks , Moguls , Portuguese , British , French , Dutch , came looted u , took .', 'Yet done nation .', 'We conquered anyone .', 'We grabbed land , culture , history tried enforce way life .', 'Why ?', 'Because respect freedom others.That first vision freedom .', 'I believe India got first vision 1857 , started War Independence .', 'It freedom must protect nurture build .', 'If free , one respect u .', 'My second vision India ’ development .', 'For fifty year developing nation .', 'It time see developed nation .', 'We among top 5 nation world term GDP .', 'We 10 percent growth rate area .', 'Our poverty level falling .', 'Our achievement globally recognised today .', 'Yet lack self-confidence see developed nation , self-reliant self-assured .', 'Isn ’ incorrect ?', 'I third vision .', 'India must stand world .', 'Because I believe unless 

In [31]:
print(corpus)

['three vision india', 'year histori peopl world come invad u captur land conquer mind', 'alexand onward greek turk mogul portugues british french dutch came loot u took', 'yet done nation', 'conquer anyon', 'grab land cultur histori tri enforc way life', '', 'respect freedom other first vision freedom', 'believ india got first vision start war independ', 'freedom must protect nurtur build', 'free one respect u', 'second vision india develop', 'fifti year develop nation', 'time see develop nation', 'among top nation world term gdp', 'percent growth rate area', 'poverti level fall', 'achiev global recognis today', 'yet lack self confid see develop nation self reliant self assur', 'incorrect', 'third vision', 'india must stand world', 'believ unless india stand world one respect u', 'strength respect strength', 'must strong militari power also econom power', 'must go hand hand', 'good fortun work three great mind', 'dr vikram sarabhai dept', 'space professor satish dhawan succeed dr brah

In [32]:
corpus = []
for i in range(len(sent)):
  review = re.sub('[^a-zA-Z]', ' ', sent[i])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

In [33]:
print(corpus)

['three vision india', 'year history people world come invaded u captured land conquered mind', 'alexander onwards greek turk mogul portuguese british french dutch came looted u took', 'yet done nation', 'conquered anyone', 'grabbed land culture history tried enforce way life', '', 'respect freedom others first vision freedom', 'believe india got first vision started war independence', 'freedom must protect nurture build', 'free one respect u', 'second vision india development', 'fifty year developing nation', 'time see developed nation', 'among top nation world term gdp', 'percent growth rate area', 'poverty level falling', 'achievement globally recognised today', 'yet lack self confidence see developed nation self reliant self assured', 'incorrect', 'third vision', 'india must stand world', 'believe unless india stand world one respect u', 'strength respect strength', 'must strong military power also economic power', 'must go hand hand', 'good fortune worked three great mind', 'dr vi

In [34]:
# Creating the Bag of words model
from sklearn.feature_extraction.text import CountVectorizer   # Data Preprocessing Libraries
cv = CountVectorizer()   # Intialize CountVectorizer
X = cv.fit_transform(corpus).toarray()

In [35]:
X.shape

(31, 115)

In [36]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#**Term Frequency-Inverse Document Frequency(TF-IDF)**
is a numerical statistic used to evaluate the importance of a word in a document within a collection of documents (a corpus). It's a way to determine how relevant a specific word is to a document, taking into account both its frequency in that document and its rarity across the entire corpus.

In [37]:
# import necessary libraries
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [38]:
ps = PorterStemmer()
wordnet = WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)

In [39]:
corpus = []
for i in range(len(sent)):
  review = re.sub('[^a-zA-Z]', ' ', sent[i])  # Removing all punctuations, signs
  review = review.lower()  # lower all sentences
  review = review.split()  # Having list of words
  review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

In [40]:
# Creating the TF - IDF model
from sklearn.feature_extraction.text import TfidfVectorizer   # Data Preprocessing Libraries
cv = TfidfVectorizer()   # Intialize TfidfVectorizer
X = cv.fit_transform(corpus).toarray()

In [41]:
X.shape

(31, 115)

In [42]:
print(sent)

['I three vision India .', 'In 3000 year history , people world come invaded u , captured land , conquered mind .', 'From Alexander onwards , Greeks , Turks , Moguls , Portuguese , British , French , Dutch , came looted u , took .', 'Yet done nation .', 'We conquered anyone .', 'We grabbed land , culture , history tried enforce way life .', 'Why ?', 'Because respect freedom others.That first vision freedom .', 'I believe India got first vision 1857 , started War Independence .', 'It freedom must protect nurture build .', 'If free , one respect u .', 'My second vision India ’ development .', 'For fifty year developing nation .', 'It time see developed nation .', 'We among top 5 nation world term GDP .', 'We 10 percent growth rate area .', 'Our poverty level falling .', 'Our achievement globally recognised today .', 'Yet lack self-confidence see developed nation , self-reliant self-assured .', 'Isn ’ incorrect ?', 'I third vision .', 'India must stand world .', 'Because I believe unless 

In [37]:
print(X)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.25883507 0.30512561 0.        ]
 [0.         0.28867513 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


#**Word2Vec**
Word2vec is a technique in natural language processing (NLP) for obtaining vector representations of words. These vectors capture information about the meaning of the word based on the surrounding words. The word2vec algorithm estimates these representations by modeling text in a large corpus.

In [38]:
# Uninstall gensim and numpy completely
!pip uninstall -y gensim numpy

Found existing installation: numpy 2.0.2
Uninstalling numpy-2.0.2:
  Successfully uninstalled numpy-2.0.2


In [39]:
# Reinstall gensim and numpy, allowing pip to find compatible versions
!pip install --no-cache-dir --upgrade gensim numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 157.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 110.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 69.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 105.9 MB/s eta 0:00:00
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is inc

In [43]:
# import necesary libraries
from gensim.models import Word2Vec
from nltk.corpus import stopwords
import re

In [44]:
# Preprocessing the data
text = re.sub(r'\[[0-9]*\]', ' ', paragraph)
text = re.sub(r'\s+', ' ', text) # rmoving unnecessary spaces
text = text.lower()
text = re.sub(r'\d', ' ', text)
text = re.sub(r'\s+', ' ', text)

In [45]:
print(text)

i have three visions for india. in years of our history, people from all over the world have come and invaded us, captured our lands, conquered our minds. from alexander onwards, the greeks, the turks, the moguls, the portuguese, the british, the french, the dutch, all of them came and looted us, took over what was ours. yet we have not done this to any other nation. we have not conquered anyone. we have not grabbed their land, their culture, their history and tried to enforce our way of life on them. why? because we respect the freedom of others.that is why my first vision is that of freedom. i believe that india got its first vision of this in , when we started the war of independence. it is this freedom that we must protect and nurture and build on. if we are not free, no one will respect us. my second vision for india’s development. for fifty years we have been a developing nation. it is time we see ourselves as a developed nation. we are among the top nations of the world in terms

In [46]:
# Preparing  the dataset
sent = nltk.sent_tokenize(text)

In [47]:
sent = [nltk.word_tokenize(sentence) for sentence in sent]
print(sent)

[['i', 'have', 'three', 'visions', 'for', 'india', '.'], ['in', 'years', 'of', 'our', 'history', ',', 'people', 'from', 'all', 'over', 'the', 'world', 'have', 'come', 'and', 'invaded', 'us', ',', 'captured', 'our', 'lands', ',', 'conquered', 'our', 'minds', '.'], ['from', 'alexander', 'onwards', ',', 'the', 'greeks', ',', 'the', 'turks', ',', 'the', 'moguls', ',', 'the', 'portuguese', ',', 'the', 'british', ',', 'the', 'french', ',', 'the', 'dutch', ',', 'all', 'of', 'them', 'came', 'and', 'looted', 'us', ',', 'took', 'over', 'what', 'was', 'ours', '.'], ['yet', 'we', 'have', 'not', 'done', 'this', 'to', 'any', 'other', 'nation', '.'], ['we', 'have', 'not', 'conquered', 'anyone', '.'], ['we', 'have', 'not', 'grabbed', 'their', 'land', ',', 'their', 'culture', ',', 'their', 'history', 'and', 'tried', 'to', 'enforce', 'our', 'way', 'of', 'life', 'on', 'them', '.'], ['why', '?'], ['because', 'we', 'respect', 'the', 'freedom', 'of', 'others.that', 'is', 'why', 'my', 'first', 'vision', 'is'

In [48]:
for i in range(len(sent)):
  sent[i] = [word for word in sent[i] if word not in stopwords.words('english')]

In [49]:
# Training the Word2Vec model
model = Word2Vec(sent, min_count=1)

In [50]:
#words = model.wv.vocab

# In Gensim 4.0.0 and later, .wv.vocab was removed.
# Use .wv.index_to_key to get a list of words in the vocabulary.
words = model.wv.index_to_key
print(words)

['.', ',', 'india', 'us', 'vision', 'must', 'nation', 'world', 'three', 'respect', 'freedom', 'see', 'developed', 'dr.', 'first', 'one', 'believe', '’', 'yet', 'worked', 'great', 'strength', 'years', 'history', 'minds', 'power', '?', 'life', 'conquered', 'way', 'war', 'others.that', 'got', 'started', 'tried', 'independence', 'protect', 'nurture', 'build', 'free', 'enforce', 'took', 'culture', 'turks', 'visions', 'people', 'come', 'invaded', 'captured', 'lands', 'alexander', 'onwards', 'greeks', 'moguls', 'land', 'portuguese', 'british', 'french', 'dutch', 'came', 'looted', 'done', 'anyone', 'grabbed', 'second', 'career', 'development', 'satish', 'military', 'also', 'economic', 'go', 'hand-in-hand', 'good', 'fortune', 'vikram', 'sarabhai', 'dept', 'space', 'professor', 'dhawan', 'fifty', 'succeeded', 'brahm', 'prakash', 'father', 'nucle', 'ar', 'material', 'lucky', 'closely', 'consider', 'opportunity', 'four', 'strong', 'respects', 'stands', 'unless', 'developing', 'milestones', 'among'

In [51]:
# Finding Word Vectors
vector = model.wv['war']

In [52]:
print(vector)

[ 2.4165460e-04  2.1676756e-03  1.0690285e-03  7.5812070e-03
 -4.4229212e-03  2.1190662e-04  7.0324880e-03  2.3337649e-03
  4.2473278e-03  4.2524766e-03 -1.2552709e-03 -8.3866576e-03
  3.0478837e-03 -8.8217482e-03 -2.6007430e-03 -9.3721049e-03
 -4.7881459e-04 -7.8417258e-03  7.4105579e-03 -4.9285530e-03
  9.9296700e-03 -9.0378430e-03 -4.2626709e-03  1.8824078e-03
 -2.9907234e-03  1.4772484e-03 -3.7016990e-03 -8.9739187e-04
 -5.7188114e-03 -9.8435655e-03  6.3726329e-03  3.6007329e-04
  6.5717809e-03 -7.4813031e-03  3.6567464e-03 -9.8930076e-03
  7.6421951e-03  5.9152138e-03 -6.0948152e-03  8.1808297e-03
 -5.5653895e-03 -8.5595474e-03  1.5177754e-03  3.1912578e-03
 -8.0998959e-03 -8.9382418e-03  9.1280146e-03  1.6407047e-03
  8.9121680e-04  2.4763066e-03 -3.5008881e-03  1.6929940e-03
  1.9376142e-03  9.7804833e-03 -5.5498732e-03  2.3099594e-03
  6.3505210e-03 -6.6789193e-03 -8.9453561e-03  8.6747240e-03
  6.8037580e-03 -4.0113861e-03  5.7603321e-03  8.3106384e-04
 -5.0508413e-03 -1.26273

In [53]:
# Most similar words
similar = model.wv.most_similar('war')
print(similar)

[('great', 0.1875634640455246), ('see', 0.18336154520511627), ('came', 0.18106915056705475), ('vision', 0.17510490119457245), ('must', 0.1629539430141449), ('military', 0.15946468710899353), ('protect', 0.15910033881664276), ('.', 0.1538781076669693), ('career', 0.14721250534057617), ('nations', 0.14415255188941956)]


In [54]:
# Most similar words
similar = model.wv.most_similar('freedom')
print(similar)

[('turks', 0.26965928077697754), ('time', 0.2351580262184143), ('today', 0.2103312909603119), ('self-assured', 0.1784987598657608), ('fortune', 0.15476417541503906), ('independence', 0.1432177573442459), ('incorrect', 0.14239166676998138), ('developed', 0.1306220293045044), ('development', 0.12988753616809845), ('achievements', 0.12734702229499817)]


In [55]:
# Most similar words
similar = model.wv.most_similar('vikram')
print(similar)

[('visions', 0.18159151077270508), ('percent', 0.16572311520576477), ('took', 0.1649642139673233), ('minds', 0.1646891087293625), (',', 0.16077134013175964), ('respects', 0.14747004210948944), ('unless', 0.14648258686065674), ('development', 0.13807044923305511), ('’', 0.1376371532678604), ('got', 0.13318757712841034)]
