## **Word Embedding Techniques using Embedding Layer in Keras**

In [2]:
!pip install tensorflow

In [2]:
### tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### Sentences
sentence = [ "the glass of milk",
            "the glass of juice",
            "the cup of tea",
            'I am a good boy',
            "I am a good developer",
            "Understand the meaning of work",
            "Your videos are good",
            "How are you",
             "The rain water is much",
             "The school gate is open"]

sentence

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of work',
 'Your videos are good',
 'How are you',
 'The rain water is much',
 'The school gate is open']

In [6]:
### vocabulary size
vocab_size = 1000

#### **One Hot Representation**

In [10]:
one_hot_rep = [one_hot(word,vocab_size) for word in sentence]
print(one_hot_rep)

[[955, 801, 257, 426], [955, 801, 257, 259], [955, 817, 257, 937], [905, 884, 426, 631, 436], [905, 884, 426, 631, 250], [554, 955, 174, 257, 809], [392, 997, 83, 631], [904, 83, 592], [955, 832, 691, 778, 140], [955, 120, 726, 778, 781]]


###**Word Embedding Representation**

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [13]:
sentence_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)  # padding "pre" will add zero in the front of matrix
print(embedded_docs)

[[  0   0   0   0 955 801 257 426]
 [  0   0   0   0 955 801 257 259]
 [  0   0   0   0 955 817 257 937]
 [  0   0   0 905 884 426 631 436]
 [  0   0   0 905 884 426 631 250]
 [  0   0   0 554 955 174 257 809]
 [  0   0   0   0 392 997  83 631]
 [  0   0   0   0   0 904  83 592]
 [  0   0   0 955 832 691 778 140]
 [  0   0   0 955 120 726 778 781]]


In [15]:
dim = 15

In [17]:
model = Sequential()
model.add(Embedding(vocab_size,15,input_length=sentence_length))
model.compile('adam','mse')

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step
[[[ 0.00605525  0.03530734 -0.03181881 ...  0.0126907  -0.03525586
   -0.04964633]
  [ 0.00605525  0.03530734 -0.03181881 ...  0.0126907  -0.03525586
   -0.04964633]
  [ 0.00605525  0.03530734 -0.03181881 ...  0.0126907  -0.03525586
   -0.04964633]
  ...
  [ 0.01676569 -0.03367358  0.00822331 ...  0.0054523   0.03011401
    0.0262784 ]
  [-0.01480579  0.03714675 -0.03525083 ...  0.03093629 -0.04978081
    0.01483419]
  [-0.0272481   0.00642117  0.02507093 ... -0.01851424 -0.02352105
    0.03599398]]

 [[ 0.00605525  0.03530734 -0.03181881 ...  0.0126907  -0.03525586
   -0.04964633]
  [ 0.00605525  0.03530734 -0.03181881 ...  0.0126907  -0.03525586
   -0.04964633]
  [ 0.00605525  0.03530734 -0.03181881 ...  0.0126907  -0.03525586
   -0.04964633]
  ...
  [ 0.01676569 -0.03367358  0.00822331 ...  0.0054523   0.03011401
    0.0262784 ]
  [-0.01480579  0.03714675 -0.03525083 ...  0.03093629 -0.04978081
    0.01483419]
  [-0.02561867  0.0078611  -0.0152

In [19]:
embedded_docs[0]

array([  0,   0,   0,   0, 955, 801, 257, 426], dtype=int32)

In [20]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[ 0.00605525  0.03530734 -0.03181881  0.03008496 -0.01174898  0.03416808
  -0.00633986 -0.00289791  0.01996479  0.04062364  0.01173155 -0.04775422
   0.0126907  -0.03525586 -0.04964633]
 [ 0.00605525  0.03530734 -0.03181881  0.03008496 -0.01174898  0.03416808
  -0.00633986 -0.00289791  0.01996479  0.04062364  0.01173155 -0.04775422
   0.0126907  -0.03525586 -0.04964633]
 [ 0.00605525  0.03530734 -0.03181881  0.03008496 -0.01174898  0.03416808
  -0.00633986 -0.00289791  0.01996479  0.04062364  0.01173155 -0.04775422
   0.0126907  -0.03525586 -0.04964633]
 [ 0.00605525  0.03530734 -0.03181881  0.03008496 -0.01174898  0.03416808
  -0.00633986 -0.00289791  0.01996479  0.04062364  0.01173155 -0.04775422
   0.0126907  -0.03525586 -0.04964633]
 [ 0.02416312 -0.00251941  0.02962584 -0.0026494  -0.03713433  0.03798086
   0.00449113  0.03442533 -0.00539141 -0.02866324  0.04061898  0.00535946
   0.02626225 -0.0110157   0.03147936]
 [ 0.01676569 -0.03367358  